### ISSUE TITLE
Linux Platform

### ISSUE THREAD

**Issue by DongPhamBK** [localizely/flutter-intl-plugin-sample-app#9] opened 2022-12-21 07:34 UTC
Will the plugin help me create multi-language apps on Linux platform? I want to develop my application on Linux platform in the future.

**Comment by lzoran** [comment] 2022-12-22 12:17
Closing this as duplicate of [issue#92](https://github.com/localizely/flutter-intl-intellij/issues/92).

**Closed as completed by lzoran** 2022-12-22 12:17 UTC
